Repository ORNL/HydraGNN, pull requests merged in 2021-12, with the labels that each got.

#11 Add edge lengths
  hydragnn/models/Base.py
  hydragnn/models/PNAStack.py
  hydragnn/models/create.py
  hydragnn/preprocess/serialized_dataset_loader.py
  tests/test_graphs.py
Labels: enhancement

#53 FIXED column indexing to access charge density and compute charge transfer
  hydragnn/preprocess/raw_dataset_loader.py
Labels: bug

#55 import os was missing
  hydragnn/utils/config_utils.py
Labels: bug

#58 update load_existing_model
  hydragnn/utils/model.py
Labels: bug

#45 Add scaled by num_nodes option for feature prediction in variable graph size
  examples/lsms/lsms.json
  hydragnn/postprocess/__init__.py
  hydragnn/postprocess/postprocess.py
  hydragnn/preprocess/raw_dataset_loader.py
Labels: enhancement

#69 mapping of PNA degree tensor to GPU
  hydragnn/utils/model.py
Labels: bug

#63 added dashed red diagonal on scatterplot
  hydragnn/postprocess/visualizer.py
Labels: enhancement

#76 Add `precommit`
  .pre-commit-config.yaml
  CONTRIBUTING.md
  requirements-dev.txt
Labels: enhancement

#82 Fixing bug in normalization
  hydragnn/postprocess/postprocess.py
  hydragnn/run_prediction.py
  hydragnn/utils/config_utils.py
Labels: bug

#84 citation file added
  CITATION.cff
Labels: documentation
