Repository ORNL/HydraGNN, pull requests merged in 2022-09, with the labels that each got.

#147 Lsms example
  examples/lsms/lsms.json
  examples/lsms/lsms.py
  hydragnn/train/train_validate_test.py
  hydragnn/utils/config_utils.py
Labels: bug, enhancement

#148 use_zero_redundancy flag added to enable ZeroRedundancyOptimizer
  examples/csce/csce_gap.json
  examples/csce/train_gap.py
  examples/eam/NiNb_EAM_bulk.json
  examples/eam/NiNb_EAM_bulk_multitask.json
  examples/eam/NiNb_EAM_energy.json
  examples/eam/NiNb_EAM_multitask.json
  examples/ising_model/ising_model.json
  examples/ising_model/train_ising.py
  examples/lsms/lsms.json
  examples/md17/md17.json
  examples/md17/md17.py
  examples/ogb/ogb_gap.json
  examples/ogb/train_gap.py
  examples/qm9/qm9.json
  examples/qm9/qm9.py
  hydragnn/run_training.py
  hydragnn/train/train_validate_test.py
  hydragnn/utils/config_utils.py
  hydragnn/utils/distributed.py
  hydragnn/utils/model.py
  hydragnn/utils/optimizer.py
  tests/inputs/ci.json
  tests/inputs/ci_multihead.json
  tests/inputs/ci_vectoroutput.json
  tests/test_optimizer.py
Labels: enhancement

#149 import pandas removed from test_enthalpy.py
  tests/test_enthalpy.py
Labels: bug
