Repository ORNL/HydraGNN, pull requests merged in 2024-11, with the labels that each got.

#305 Light refactor to improve development
  hydragnn/models/Base.py
  hydragnn/models/CGCNNStack.py
  hydragnn/models/DIMEStack.py
  hydragnn/models/EGCLStack.py
  hydragnn/models/GATStack.py
  hydragnn/models/GINStack.py
  hydragnn/models/MACEStack.py
  hydragnn/models/MFCStack.py
  hydragnn/models/PAINNStack.py
  hydragnn/models/PNAEqStack.py
  hydragnn/models/PNAPlusStack.py
  hydragnn/models/PNAStack.py
  hydragnn/models/SAGEStack.py
  hydragnn/models/SCFStack.py
  hydragnn/models/create.py
Labels: documentation, enhancement

#281 Alexandria add download bash script
  examples/alexandria/alexandria_energy.json
  examples/alexandria/alexandria_forces.json
  examples/alexandria/download_dataset.sh
  examples/alexandria/train.py
Labels: enhancement

#307 Reformatting MACE
  hydragnn/models/Base.py
  hydragnn/models/MACEStack.py
  hydragnn/utils/model/irreps_tools.py
  hydragnn/utils/model/mace_utils/modules/blocks.py
Labels: enhancement

#306 Fix pbc conv args Final Draft
  examples/LennardJones/LJ_data.py
  hydragnn/models/DIMEStack.py
  hydragnn/models/EGCLStack.py
  hydragnn/models/MACEStack.py
  hydragnn/models/PAINNStack.py
  hydragnn/models/PNAEqStack.py
  hydragnn/models/PNAPlusStack.py
  hydragnn/models/SCFStack.py
  hydragnn/preprocess/graph_samples_checks_and_updates.py
  hydragnn/preprocess/serialized_dataset_loader.py
  hydragnn/utils/datasets/abstractrawdataset.py
  hydragnn/utils/input_config_parsing/config_utils.py
  hydragnn/utils/model/operations.py
  tests/test_periodic_boundary_conditions.py
Labels: bug

#295 omat24 example
  examples/omat24/download_dataset.py
  examples/omat24/example_requirements.txt
  examples/omat24/omat24_energy.json
  examples/omat24/omat24_forces.json
  examples/omat24/train.py
Labels: enhancement

#310 edge_dim added as argument to GATv2Conv
  examples/md17/md17.json
  examples/md17/md17.py
  examples/qm9/qm9.json
  examples/qm9/qm9.py
  hydragnn/models/Base.py
  hydragnn/models/GATStack.py
  hydragnn/models/PNAEqStack.py
  hydragnn/models/create.py
  hydragnn/utils/input_config_parsing/config_utils.py
  hydragnn/utils/model/model.py
  tests/inputs/ci_vectoroutput.json
  tests/test_examples.py
  tests/test_graphs.py
Labels: enhancement
